### ISSUE TITLE
Compile errors on windows

### ISSUE THREAD

**Issue by xxshady** [matklad/backtrace-on-stack-overflow#2]
Do you know why i have this errors? I'm trying to use your crate on Windows 11.

![изображение](https://github.com/matklad/backtrace-on-stack-overflow/assets/54737754/a8dd8503-8fdb-4933-9203-5b801cb06595)

**Comment by matklad** [comment]
windows 11 doesn't have signals, this crate is unix-only. I _think_ something similar should be possible to do on windows, but I don't know off hand how.

**Comment by xxshady** [comment]
Oh, thanks for response, I will try to find something to get it to work on windows

**Comment by mtshiba** [comment]
> Oh, thanks for response, I will try to find something to get it to work on windows

I have implemented a Windows port of backtrace-on-stack-overflow. If you are still having trouble, give it a try.

https://github.com/mtshiba/w-boson

**Comment by xxshady** [comment]
wow, thank you! i will definitely try it

**Comment by xxshady** [comment]
i guess this issue can be closed then
